language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install markdown_link_extractor testfixtures pyyaml
# command to run tests
script:
  - python .ci/check_scripts.py
  - if $(git diff --name-only HEAD..$TRAVIS_BRANCH | grep -q ".ci"); then pytest .ci/; fi
